##############################################################################
#
# GitGub CI workflow syntax spec:
#    https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions
#
# CodeCov github action setup:
#    https://github.com/codecov/codecov-action
#
# CodeCov badge setup:
#    https://docs.codecov.com/docs/status-badges
#
# version 1.1
##############################################################################
name: Run Unit Test and Upload Coverage Report
on:
  # Triggered whenever push to master 
  push:
    branches: [ "master" ]
  # Triggered whenever a pull request is created on master
  pull_request:
    branches: [ "master" ]
    types: [opened]
  # Allow manual trigger
  workflow_dispatch:
jobs:
  build-run-upload:
    # Create a container of the latest Ubuntu, other values could be
    # ubuntu-latest, ubuntu-22.04, etc.
    runs-on: ubuntu-20.04      # any ubuntu that has docker
    defaults:
      run:
        shell: bash       # specify bash for use with docker container
    container:
      image: osrf/ros:galactic-desktop # use ROS Galactic from docker hub repository
    steps:
      # Create a common directory for both repositories
      - name: Create common directory
        run: mkdir -p ${{ github.workspace }}/ros2_ws/src
      # We want to use GitHub CI checkout version 3 to check out our branch
      - uses: actions/checkout@v3
        with:
          path: ros2_ws/src/CollectionBot
      # Clone and set up ARIAC package in the common directory
      - name: Clone ARIAC package
        run: |
          git clone https://github.com/usnistgov/ARIAC.git ${{ github.workspace }}/ros2_ws/src/ariac
          # Add any necessary setup steps for ARIAC here
      - name: Clone Collection Bot package
        run: |
          git clone https://github.com/kirangit27/FP808XG6--CollectionBot ${{ github.workspace }}/ros2_ws/src/collection_bot
          cd ${{ github.workspace }}/ros2_ws/src/collection_bot/
          # Add any necessary setup steps for ARIAC here
          
      - name: Install system and ROS dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-rosdep openjdk-17-jdk
          # sudo rosdep init
          rosdep update --include-eol-distros
        
      - name: Install ARIAC dependencies with rosdep
        run: |
          cd ${{ github.workspace }}/ros2_ws
          rosdep install --from-paths src -y --ignore-src
      # Install some system packages
      - name: Install build packages
        run: |
          sudo apt update
          sudo apt install -y doxygen lcov gcovr pandoc ros-galactic-gazebo-ros-pkgs ros-galactic-navigation2 ros-galactic-nav2-bringup ros-galactic-moveit
      # Build the ROS2 packages
      - name: Build ROS2 packages
        run: |
          source /opt/ros/galactic/setup.bash
          cd ${{ github.workspace }}/ros2_ws
          colcon build --symlink-install
      # Run all unit test, integration test, and generate combined coverage report
      - name: Build, run unit test, and generate coverage report
        run: |
          source /opt/ros/galactic/setup.bash
          cd ${{ github.workspace }}/ros2_ws
          colcon build --packages-select ariac_collection_bot --cmake-args -DCOVERAGE=ON 
          source install/setup.bash
          colcon test --packages-select ariac_collection_bot
          colcon test-result --test-result-base build/ariac_collection_bot/ 
          
      - name: Generate test coverage report
        run: |
          source /opt/ros/galactic/setup.bash
          cd ${{ github.workspace }}/ros2_ws
          colcon build --packages-select ariac_collection_bot
          source install/setup.bash
          ros2 run ariac_collection_bot generate_coverage_report.bash
          
      - name: List coverage files
        run: |
          ls -l ${{ github.workspace }}/ros2_ws/install/ariac_collection_bot/lib/ariac_collection_bot/
          chmod +x ${{ github.workspace }}/ros2_ws/install/ariac_collection_bot/lib/ariac_collection_bot/coverage_cleaned.info
          
      - name: Upload coverage result using bash uploader
        run: |
          curl -s https://codecov.io/bash > codecov.sh
          chmod +x codecov.sh
          ./codecov.sh -t ${{ secrets.CODECOV_TOKEN }} -f ${{ github.workspace }}/ros2_ws/install/ariac_collection_bot/lib/ariac_collection_bot/coverage_cleaned.info

